---
title: "Heatmap_Plots"
author: "Abigail Booth"
date: "November 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Heatmap plots

```{r}
library("phyloseq")
library("ggplot2")
theme_set(theme_bw())
```
```{r}
data("GlobalPatterns")
gpt <- subset_taxa(GlobalPatterns, Kingdom=="Bacteria")
gpt <- prune_taxa(names(sort(taxa_sums(gpt),TRUE)[1:300]), gpt)
plot_heatmap(gpt, sample.label="SampleType")
```
```{r}
gpac <- subset_taxa(GlobalPatterns, Phylum=="Crenarchaeota")
```

### Default plot_heatmap settings

```{r}
plot_heatmap(gpac)
```
```{r}
# Relabel by sample variable and taxonomic family
(p <- plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family"))
```
```{r}
# relabel axis titles
p$scales$scales[[1]]$name <- "My X-Axis"
p$scales$scales[[2]]$name <- "My Y-Axis"
print(p)
```
```{r}
# change color scheme
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#CCFF66")
```
```{r}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#FF3300")
```
```{r}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#000033", high="#66CCFF")
```
```{r}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#66CCFF", high="#000033", na.value="white")
```
```{r}
plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family", low="#FFFFCC", high="#000033", na.value="white")
```
```{r}
# Now w/ different ordination methods, distances
plot_heatmap(gpac, "NMDS", "jaccard")
```
```{r}
plot_heatmap(gpac, "DCA", "none", "SampleType", "Family")
```
```{r}
plot_heatmap(gpac, "RDA", "none", "SampleType", "Family")
```
```{r}
plot_heatmap(gpac, "PCoA", "bray", "SampleType", "Family")
```
```{r}
plot_heatmap(gpac, "PCoA", "unifrac", "SampleType", "Family")
```
```{r}
plot_heatmap(gpac, "MDS", "unifrac", "SampleType", "Family", weighted=TRUE)
```
```{r}
heatmap(otu_table(gpac))
```

