---
title: "Lab 12"
author: "Abigail Booth"
date: "November 16, 2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cytoscape 
  
  * [Basic Data Visualization](images/cytoscape_blv.png)
  
  * Differentially Expressed Genes
      - [Ex 1 - up-regulated genes](images/cytoscape_up_Ex1.png)
      - [Ex 1 - down-regulated genes](images/cytoscape_down_ex1.png)
      - [Ex 2](images/cytoscape_DE_ex2.png)
      
RCy3
```{r}
library(RCy3)
cytoscapePing()
```
```{r}
nodes <- data.frame(id=c("node 0","node 1","node 2","node 3"),
           group=c("A","A","B","B"), # categorical strings
           score=as.integer(c(20,10,15,5)), # integers
           stringsAsFactors=FALSE)
edges <- data.frame(source=c("node 0","node 0","node 0","node 2"),
           target=c("node 1","node 2","node 3","node 3"),
           interaction=c("inhibits","interacts","activates","interacts"),  # optional
           weight=c(5.1,3.0,5.2,9.9), # numeric
           stringsAsFactors=FALSE)

createNetworkFromDataFrames(nodes,edges, title="my first network", collection="DataFrame Example")
```
```{r}
setVisualStyle('Marquee')
```
```{r}
style.name = "myStyle"
defaults <- list(NODE_SHAPE="diamond",
                 NODE_SIZE=30,
                 EDGE_TRANSPARENCY=120,
                 NODE_LABEL_POSITION="W,E,c,0.00,0.00")
nodeLabels <- mapVisualProperty('node label','id','p')
nodeFills <- mapVisualProperty('node fill color','group','d',c("A","B"), c("#FF9900","#66AAAA"))
arrowShapes <- mapVisualProperty('Edge Target Arrow Shape','interaction','d',c("activates","inhibits","interacts"),c("Arrow","T","None"))
edgeWidth <- mapVisualProperty('edge width','weight','p')

createVisualStyle(style.name, defaults, list(nodeLabels,nodeFills,arrowShapes,edgeWidth))
setVisualStyle(style.name)
```
```{r, eval=FALSE}
g = new('graphNEL', edgemode='directed')
g = graph::addNode('A', g)
g = graph::addNode('D', g)
g = graph::addNode('C', g, edges = list('D'))
g = graph::addNode('B', g, edges = list(c('A','D','C')))
createNetworkFromGraph(g, title='simple network', collection='GraphNEL Example')

# add node attributes
df <- data.frame (moleculeType=c('kinase','TF','cytokine','cytokine'),
                 log2fc=c(1.8,3.0,-1.2,-2.5),
                 row.names = c('A','B','C','D'), # row.names = node names
                 stringsAsFactors = FALSE)       # important when loading strings!
loadTableData (df)

setNodeShapeDefault ('OCTAGON')
setNodeColorDefault ('#AAFF88')
setNodeSizeDefault  (60)
setNodeFontSizeDefault (30)

getNodeShapes ()   # diamond, ellipse, trapezoid, triangle, etc.
column <- 'moleculeType'
values <- c ('kinase',  'TF','cytokine')
shapes <- c ('DIAMOND', 'TRIANGLE', 'RECTANGLE')
setNodeShapeMapping (column, values, shapes)

column <- 'log2fc'
control.points <- c (-3.0, 0.0, 3.0)
colors <-  c ('#5588DD', '#FFFFFF', '#DD8855')
setNodeColorMapping (column, control.points, colors)

control.points <- c (-2.0, 0.0, 2.0)
colors <-  c ('#2255CC', '#5588DD', '#FFFFFF', '#DD8855','#CC5522')
setNodeColorMapping (column, control.points, colors)

control.points = c (-3.0, 2.0, 3.0)
sizes     = c (20, 80, 90)
setNodeSizeMapping (column, control.points, sizes)
```

### Selecting nodes

```{r}
selectNodes('C', 'name')
getSelectedNodes()
```
```{r}
selectFirstNeighbors()
```
```{r}
node.names <- getSelectedNodes()
```
```{r}
clearSelection()
```

### Saving and export

```{r}
saveSession('vignette_session') #.cys
```
```{r}
full.path=paste(getwd(),'vignette_image',sep='/')
exportImage(full.path, 'PNG', zoom=200) #.png scaled by 200%
exportImage(full.path, 'PDF') #.pdf
```



