---
title: "Lab3B"
author: "Abigail Booth"
date: "September 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```
```{r}
surveys <- read_csv("data/portal_data_joined.csv")
```
```{r}
str(surveys)
```
```{r}
View(surveys)
```
```{r}
select(surveys, plot_id, species_id, weight)
```
```{r}
select(surveys, -record_id, -species_id)
```
```{r}
filter(surveys, year == 1995)
```
### Pipes 
```{r}
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
```
This is the same as:
```{r}
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
```
```{r}
surveys %>% 
  filter(weight < 5) %>% 
  select(species_id, sex, weight)
```
```{r}
surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
surveys_sml
```
### Challenge: Pipes
```{r}
piped_surveys <- surveys %>%
  filter(year < 1995) %>% 
  select(year, sex, weight)
piped_surveys
```
### Mutate
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```
### Challenge: Mutate
```{r}
surveys %>%
  filter(!is.na(hindfoot_length)) %>% 
  mutate(hindfoot_cm = (hindfoot_length / 10)) %>%
  filter(hindfoot_cm < 3) %>%
  select(species_id, hindfoot_cm)
```
### Split-apply-combine data analysis and the summarize() function
```{r}
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```
```{r}
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>%
  tail()
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
```
```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))
```
```{r}
surveys %>%
  count(sex, sort = TRUE)
```
```{r}
surveys %>%
  count(sex, species)
```
```{r}
surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```
### Challenge: Split-apply-combine data analysis and the summarize() function
1. 
```{r}
surveys %>%
  count(plot_type)
```
2. 
```{r}
surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  group_by(species_id) %>%
  summarize(
    mean_hindfoot_length = mean(hindfoot_length),
    min_hindfoot_length = min(hindfoot_length),
    max_hindfoot_length = max(hindfoot_length),
    n = n()
    )
```
3. 
```{r}
surveys %>%
  filter(!is.na(weight)) %>% 
  group_by(year) %>%
  filter(weight == max(weight)) %>%
  arrange(year) %>% 
  select(year, genus, species_id, weight)
```
### Reshaping with gather and spread
```{r}
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))
```
```{r}
str(surveys_gw)
```
```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)
str(surveys_spread)
```
```{r}
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```
```{r}
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)
str(surveys_gather)
```
```{r}
surveys_spread %>%
  gather(key = "genus", value = "mean_weight", Baiomys:Spermophilus) %>%
  head()
```
### Challenge: Reshaping with Gather and Spread
1. 
```{r}
spread_genera_surveys <- surveys %>%
  group_by(year, plot_id) %>%
  summarize(num_genera = n_distinct(genus)) %>% 
  spread(year, num_genera) 
head(spread_genera_surveys)
```
2.
```{r}
spread_genera_surveys %>%
  gather(key = "year", value = "num_genera", -plot_id)
```
3.
```{r}
measure_surveys <- surveys %>%
  gather(key = "measurement", "value", hindfoot_length, weight)
head(measure_surveys)
```
4. 
```{r}
measure_surveys %>%
  group_by(year, measurement, plot_type) %>%
  summarize(average_measurement = mean(value, na.rm = TRUE)) %>%
  spread(key = "measurement", value = "average_measurement")
```
### Exporting data
```{r}
surveys_complete <- surveys %>%
  filter(!is.na(weight),
         !is.na(hindfoot_length),
         !is.na(sex))
```
```{r}
## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)
```
```{r}
dim(surveys_complete)
```
```{r}
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```