---
title: "lab5"
author: "Abigail Booth"
date: "September 21, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warnings=FALSE,message=FALSE}
library(tidyverse)
```

### Joining tables

```{r}
Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
str(Confirmed_State_3_13)
```
```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
str(Confirmed_State_9_13)
```
```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)
```
```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 
```
```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
tail(Confirmed_State_3_13_9_13_joined, 5)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```
```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```

### Switching between wide and long table formats

```{r, fig.width = 6, fig.height = 10}
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_point(aes(color = Date))
```

### Working with the time series data

```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
head(time_series_confirmed)
```
```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 
head(time_series_confirmed_long)
```
```{r, warnings=FALSE, message=FALSE}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
```
```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```
```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```
```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```
```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```
```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```
```{r}
which(is.na(time_series_long_joined$Confirmed))
```
```{r}
which(is.na(time_series_long_joined$Deaths))
```
```{r, warnings=FALSE,message=FALSE}
library(lubridate)
```
```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```
```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

### Making Graphs from the time series data

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```
```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```
```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```
```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```

### Exercises

2 and 3. 
```{r}
Confirmed_State_6_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>% 
  filter(Country_Region == "US") %>%
  group_by(Province_State, Country_Region) %>%
  summarize(Confirmed = sum(Confirmed))
```
```{r}
str(Confirmed_State_6_13)
```
```{r}
setdiff(Confirmed_State_6_13$Province_State, Confirmed_State_3_13$Province_State)
```
```{r}
Confirmed_State_6_13 <- Confirmed_State_6_13 %>%
  filter(Province_State != "Recovered")
```

```{r}
Confirmed_State_3_13_6_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_6_13, by = c("Province_State")) %>% 
      rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_6_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_6_13_joined)
```
```{r, fig.width = 6, fig.height = 10}
Confirmed_State_3_13_6_13_joined_long <- Confirmed_State_3_13_6_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
ggplot(Confirmed_State_3_13_6_13_joined_long, aes(x = Confirmed, y = Province_State)) +
  geom_bar(stat = "identity") +
  labs(title = "Confirmed Covid-19 Cases in US 9/13/20",
       x = "Number of Confirmed Cases",
       y = "State")
```

4.

```{r}
time_series_by_day <- time_series_long_joined %>%
  group_by(Date) %>%
  summarize(deaths = sum(Deaths),
            confirmed = sum(Confirmed))
head(time_series_by_day)
```
```{r}
ggplot(time_series_by_day, aes(x = Date, y = deaths)) +
  geom_point() +
  labs(title = "Worldwide Confirmed Covid-19 Deaths per Day",
       x = "Date",
       y = "Number of Deaths")
```

5. 

```{r}
time_series_by_day_mutated <- time_series_by_day %>%
  mutate(Deaths_per_Confirmed = deaths / confirmed) %>%
  filter(!is.na(Deaths_per_Confirmed))
head(time_series_by_day_mutated)
```
6. 

```{r}
ggplot(time_series_by_day_mutated, aes(x = Date, y = Deaths_per_Confirmed)) +
  geom_point() +
  geom_line() +
  labs(title = "Covid-19 Deaths/Confirmed Cases",
       x = "Date",
       y = "Deaths per Confirmed Cases")
```

7.

```{r}
top_country_deaths <- time_series_long_joined %>%
  group_by(Country_Region) %>%
  summarize(Deaths = sum(Deaths)) %>%
  arrange(desc(Deaths)) %>% 
  slice(1:10)
top_country_deaths
```
```{r}
time_series_long_joined %>% 
  filter(Country_Region%in%top_country_deaths$Country_Region) %>%
  ggplot(aes(x = Date, y = Deaths, color = Country_Region)) +
  geom_point() +
  labs(title = "Countries with Most Covid-19 Deaths", x = "Date", y = "Number of Covid-19 Deaths") +
  theme_bw()
```
8 & 10. 

```{r, fig.height = 4, fig.width = 7}
time_series_long_joined %>%
  group_by(Country_Region, Date) %>%
  summarize(Deaths = sum(Deaths)) %>%
  filter(Country_Region %in% c("US", "Brazil", "United Kingdom", "Italy", "Mexico", "France", "Spain", "India", "Iran", "Peru")) %>% 
  ggplot(aes(x = Date, y = Deaths)) +
  geom_line() +
  facet_wrap(vars(Country_Region), ncol = 5) +
  labs(title = "Countries with Most Covid-19 Deaths", x = "Date", y = "Number of Covid-19 Deaths") +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "grey20", size = 10, angle = 90, hjust = 0.5, vjust = 0.25),
                    axis.text.y = element_text(color = "red", size = 10),
                    text = element_text(size = 14))
```

9. 

```{r, fig.width = 5, fig.height = 4}
time_series_long_joined %>%
  group_by(Country_Region, Province_State, Date) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date, y = Confirmed)) +
  geom_line() +
  facet_wrap(vars(Country_Region)) +
  labs(title = "Confirmed US Covid-19 Cases", x = "Date", y = "Confirmed Cases") +
  theme_bw()
```
  